# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 919311f4855b14ce64e6d6ede70f755f59caaf60051217f5778f3fc9dfdfeface41e18982bb912ad971a17e3c5df38ac7cec0514d792ba5e4ff01842d6b74df6

test:
  secret_key_base: c8cb0dffc4407d096b277ce6140b05bc6be1867d28bd79b86da34da449350433704ebb1e73a6af64c427c4c9cd2b349857bfd78c588cd064e53e2210536a7503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
